/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0058be",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#adc6ff",

        "secondary": "#4648d4",
        "secondary-container": "#6063ee",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",

        "tertiary": "#006947",
        "tertiary-container": "#00855b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f5fff6",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",

        "background": "#f9f9ff",
        "on-background": "#151c27",
        "surface": "#f9f9ff",
        "on-surface": "#151c27",
        "on-surface-variant": "#424754",
        "surface-dim": "#d3daea",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#dce2f3",
        "surface-tint": "#005ac2",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",

        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",

        "outline": "#727785",
        "outline-variant": "#c2c6d6",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        unit: "4px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        title: ["Inter", "sans-serif"],
      },
      boxShadow: {
        card: "0px 4px 12px rgba(0, 0, 0, 0.03)",
        floating: "0px 12px 24px rgba(0, 0, 0, 0.08)",
        ai: "0px 12px 24px rgba(96, 99, 238, 0.15)",
      },
    },
  },
  plugins: [],
};
